services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: expense_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      TZ: Asia/Bangkok
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - expense_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: expense_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - expense_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: expense_tracker
      DB_USER: admin
      DB_PASSWORD: password123
      TZ: Asia/Bangkok
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - expense_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - expense_network
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  expense_network:
    driver: bridge